### ISSUE TITLE
Some show titles fail scanning into database

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#2]
When updating the database with upddatedb_pi,py some shows fail to scan in, a few of which worked fine in a previous version.  Unlike the episode errors that appear sporadically, these show at the end of the TV scanning output and are completely excluded from the database

Error adding Better Call Saul*
Error adding Doctor Who (2005)
Error adding Downton Abbey
Error adding The Drinky Crow Show*
Error adding The Flash (2014)*
Error adding Marvel's Agent Carter
Error adding Young Justice*

*Worked in previous version

**Comment by amazingr4b** [comment]
If you do an epdetails on one of those series shows do you get any output? Use something like- epdetails "The Drinky Crow Show" 1 1  
I need to know if you get details for the episode or something else. I think I know what is causing that.

**Comment by MoeFwacky** [comment]
epdetails gives me the info on each of the shows (except Agent Carter, but that one spits errors while scanning as well as at the end)

pi@BAD-HORSE ~/hasystem $ epdetails "young justice" 1 1
Independence Day The Plot Summary is Robin Aqualad and Kid Flash break into Cadmus and find that it is being run by Genomorphs.

here's the text from the problems log

King of the Hill AprÃ¨s Hank, le Deluge
Marvel's Agent Carter Now is Not The End
Marvel's Agent Carter Bridge and Tunnel
Marvel's Agent Carter Time and Tide
Marvel's Agent Carter The Blitzkrieg Button
Marvel's Agent Carter The Iron Ceiling
Marvel's Agent Carter A Sin to Err
Marvel's Agent Carter SNAFU
Marvel's Agent Carter Valediction
Orange Is the New Black Donât Make Me Come Back There
Star Trek: Enterprise EÂ²
Star Trek: The Next Generation DÃ©jÃ  Q
Star Trek: The Next Generation MÃ©nage Ã  Troi
Star Trek: Voyager Vis Ã  Vis
Star Trek: Voyager QÂ²
The Venture Bros. Â¡Viva los Muertos!
Better Call Saul
Doctor Who (2005)
Downton Abbey
The Drinky Crow Show
The Flash (2014)
Marvel's Agent Carter
Young Justice

**Comment by amazingr4b** [comment]
Yea, a lot of those are for characters not supported by my current setup. I think I have the "'" one fixed, but some of those others like the crazy A and copyright symbol will probably remain as ones that need manual intervention unless I find a quick and easy way to deal with them. Try the tvlist update file I recently posted to see if they get the ones with the '. There are some usage notes in its comments. The error log will give more info of where more problems are for some of those other shows.

**Comment by MoeFwacky** [comment]
Sorry for the delay, I was on vacation for a bit.

So that last block of shows at the bottom that wasn't adding, still doesn't add. Below is the output from running the tvlist update file and subsequently trying to add to a block. Also, the problems.txt (attached) file has entries for each show, unfortunately the error is nonspecific. Also, worth noting, when viewing the problems.txt file through nano over ssh, I'm seeing some of those special characters (example: the man who puts âcriminalâ in âcriminal lawyerâ)  that appear as normal when viewed through Textpad (the man who puts ‘criminal’ in ‘criminal lawyer’). I don't know if this is related, but I thought it was worth noting.
[problems.txt](https://github.com/amazingr4b/TBN-Plex/files/392509/problems.txt)


pi@BAD-HORSE ~/hasystem $ python tvlist_update.py
(u'http://192.168.1.120:32400/library/sections/2/all/',)
Database update starting...

Error adding Better Call Saul
Error adding Doctor Who (2005)
Error adding Downton Abbey
Error adding The Drinky Crow Show
Error adding The Flash (2014)
Error adding Young Justice
TV entries checked.
Done
pi@BAD-HORSE ~/hasystem $ addblock
Command line options not present. Proceeding to querry mode.
Enter New Block Name

Name: test
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4-                                                                Quit.
Choice: 2
TV Show Name:better call saul
better call saul not found in library. Did you mean:

**Comment by amazingr4b** [comment]
The problem is some character is messing up the SQL querry. I'll eventually figure out what it is and how to get around it. Odds are it is the "'". Try removing those from the summary of "better caul saul" in your plex, and see if that then doesn't error when you run the tv update.

**Comment by MoeFwacky** [comment]
Yeah, that did the trick. Scrubbed quotes, em-dasshes and accented vowels from descriptions and they scanned right in.

**Comment by amazingr4b** [comment]
This one is mostly fixed with the changes made to the 3.00x verions. The only exception is shows that have a special characters in the show title. Apostrophes shouldn't cause problems. The remaining issue affecting main title will be corrected in a future release.

**Comment by MoeFwacky** [comment]
Note sure if this is part of this issue or a separate one, but I updated the script for the first time in a while, and while updating the TV database, got this error

Using the following TV Show library: TV Shows
82.2%Traceback (most recent call last):
  File "upddatedb_pi.py", line 653, in <module>
    getshows()
  File "upddatedb_pi.py", line 381, in getshows
    totalnum = int(show.leafCount)
TypeError: int() argument must be a string or a number, not '_NA'

I'm not sure what show it could be hitting, but the only special characters in my show titles are apostrophes, colons, exclamation points, and parentheses.
Examples: 
Marvel's Agent Carter
Star Trek: Deep Space Nine
Freakazoid!
Archer (2009)

**Comment by amazingr4b** [comment]
Assuming you are using the most recent update script, that is something different. Do you have something in that library that does not have episodes? The error being thrown is where it tries to get the number of episodes a show has. If you didn't use the restoretvdb command you can probably use the listshows command and determine what item it was based on what titles are returned. I can add a few lines to get past that error, but it would be better if I knew why you were getting it to properly account for it.

**Comment by MoeFwacky** [comment]
Yeah, I updated everything today. I removed anything from the library that didn't have episodes (a single MTV Unplugged file) or had only a few non-contiguous episodes, and corrected a folder that listed it's season as "English." Though I don't think that affected it in the Plex library. I'm still getting the error, at about the same place (83.1% on the last round).

**Comment by amazingr4b** [comment]
The update script I posted a few hours ago has a exception and print that should help when that error happens. Accented characters might cause a problem, but nothing you listed would be, though I don't think that's your issue here.

**Comment by MoeFwacky** [comment]
Looks like the updated file did the trick. Just updated and ran a database update, hit 100% with no issues. A side note, the movies update completed at 100.7%. No big deal, but thought you might want to know.

**Comment by amazingr4b** [comment]
This one is getting closed. If there is an example of a title that fails to add a new case can be opened, provided the details for the item are provided in the case along with the error.
